//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Token", Namespace="http://tempuri.org/")]
    public partial class Token : object
    {
        
        private string AuthenIDField;
        
        private string UsernameField;
        
        private string SystemNameField;
        
        private System.DateTime CreateDateField;
        
        private ServiceReference1.TokenParam[] ParamsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string AuthenID
        {
            get
            {
                return this.AuthenIDField;
            }
            set
            {
                this.AuthenIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SystemName
        {
            get
            {
                return this.SystemNameField;
            }
            set
            {
                this.SystemNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ServiceReference1.TokenParam[] Params
        {
            get
            {
                return this.ParamsField;
            }
            set
            {
                this.ParamsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenParam", Namespace="http://tempuri.org/")]
    public partial class TokenParam : object
    {
        
        private string AuthenIDField;
        
        private string NameField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string AuthenID
        {
            get
            {
                return this.AuthenIDField;
            }
            set
            {
                this.AuthenIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreRequest", Namespace="http://tempuri.org/")]
    public partial class PreRequest : object
    {
        
        private string ADUserField;
        
        private string SystemIDField;
        
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ADUser
        {
            get
            {
                return this.ADUserField;
            }
            set
            {
                this.ADUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SystemID
        {
            get
            {
                return this.SystemIDField;
            }
            set
            {
                this.SystemIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationMSG", Namespace="http://tempuri.org/")]
    public partial class AuthenticationMSG : object
    {
        
        private ServiceReference1.Token TokenMessageField;
        
        private ServiceReference1.ResponseMessage MessageField;
        
        private ServiceReference1.PreRequest RequestField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ServiceReference1.Token TokenMessage
        {
            get
            {
                return this.TokenMessageField;
            }
            set
            {
                this.TokenMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ServiceReference1.ResponseMessage Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ServiceReference1.PreRequest Request
        {
            get
            {
                return this.RequestField;
            }
            set
            {
                this.RequestField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessage", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Token))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.TokenParam[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.TokenParam))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.PreRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.AuthenticationMSG))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.UserManagementMSG))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Team))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1._Team))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Employee[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Employee))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1._Employee))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Department))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1._Department))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ArrayOfString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Group[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Group))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1._Group))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Permission[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Permission))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1._Permission))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Team[]))]
    public partial class ResponseMessage : object
    {
        
        private bool IsSuccessField;
        
        private string MessageField;
        
        private object ReturnValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsSuccess
        {
            get
            {
                return this.IsSuccessField;
            }
            set
            {
                this.IsSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object ReturnValue
        {
            get
            {
                return this.ReturnValueField;
            }
            set
            {
                this.ReturnValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserManagementMSG", Namespace="http://tempuri.org/")]
    public partial class UserManagementMSG : object
    {
        
        private ServiceReference1.Team TeamField;
        
        private ServiceReference1.Employee EmployeeField;
        
        private ServiceReference1.Team[] TeamsField;
        
        private ServiceReference1.Employee[] EmployeesField;
        
        private ServiceReference1.ResponseMessage MessageField;
        
        private ServiceReference1.PreRequest RequestField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ServiceReference1.Team Team
        {
            get
            {
                return this.TeamField;
            }
            set
            {
                this.TeamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ServiceReference1.Employee Employee
        {
            get
            {
                return this.EmployeeField;
            }
            set
            {
                this.EmployeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ServiceReference1.Team[] Teams
        {
            get
            {
                return this.TeamsField;
            }
            set
            {
                this.TeamsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ServiceReference1.Employee[] Employees
        {
            get
            {
                return this.EmployeesField;
            }
            set
            {
                this.EmployeesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ServiceReference1.ResponseMessage Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ServiceReference1.PreRequest Request
        {
            get
            {
                return this.RequestField;
            }
            set
            {
                this.RequestField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Team", Namespace="http://tempuri.org/")]
    public partial class Team : ServiceReference1._Team
    {
        
        private ServiceReference1.Employee[] EmployeesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ServiceReference1.Employee[] Employees
        {
            get
            {
                return this.EmployeesField;
            }
            set
            {
                this.EmployeesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_Team", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Team))]
    public partial class _Team : object
    {
        
        private int TeamIDField;
        
        private string TH_TeamNameField;
        
        private string ENG_TeamNameField;
        
        private string DescriptionField;
        
        private string SystemIDField;
        
        private string StatusField;
        
        private string CreateByField;
        
        private System.DateTime CreateOnField;
        
        private string UpdateByField;
        
        private System.DateTime UpdateOnField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TeamID
        {
            get
            {
                return this.TeamIDField;
            }
            set
            {
                this.TeamIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TH_TeamName
        {
            get
            {
                return this.TH_TeamNameField;
            }
            set
            {
                this.TH_TeamNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ENG_TeamName
        {
            get
            {
                return this.ENG_TeamNameField;
            }
            set
            {
                this.ENG_TeamNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SystemID
        {
            get
            {
                return this.SystemIDField;
            }
            set
            {
                this.SystemIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CreateBy
        {
            get
            {
                return this.CreateByField;
            }
            set
            {
                this.CreateByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime CreateOn
        {
            get
            {
                return this.CreateOnField;
            }
            set
            {
                this.CreateOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string UpdateBy
        {
            get
            {
                return this.UpdateByField;
            }
            set
            {
                this.UpdateByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime UpdateOn
        {
            get
            {
                return this.UpdateOnField;
            }
            set
            {
                this.UpdateOnField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    public partial class Employee : ServiceReference1._Employee
    {
        
        private string BranchNameField;
        
        private ServiceReference1.Department DepartmentField;
        
        private ServiceReference1.Group[] GroupsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BranchName
        {
            get
            {
                return this.BranchNameField;
            }
            set
            {
                this.BranchNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ServiceReference1.Department Department
        {
            get
            {
                return this.DepartmentField;
            }
            set
            {
                this.DepartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ServiceReference1.Group[] Groups
        {
            get
            {
                return this.GroupsField;
            }
            set
            {
                this.GroupsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_Employee", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Employee))]
    public partial class _Employee : object
    {
        
        private string Emp_CodeField;
        
        private string ADUserField;
        
        private byte[] UserImageField;
        
        private string TH_NameField;
        
        private string ENG_NameField;
        
        private string NickNameField;
        
        private string PositionNameField;
        
        private string LevelField;
        
        private string SEXField;
        
        private string TelephoneField;
        
        private string NodeIDField;
        
        private string NodeNameField;
        
        private string DepartmentIDField;
        
        private string BranchCodeField;
        
        private string CreateByField;
        
        private System.DateTime CreateOnField;
        
        private string UpdateByField;
        
        private System.DateTime UpdateOnField;
        
        private string ActiveField;
        
        private string OfficerCodeField;
        
        private string PositionCodeField;
        
        private string EmailField;
        
        private string IDNumberField;
        
        private System.DateTime BirthDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Emp_Code
        {
            get
            {
                return this.Emp_CodeField;
            }
            set
            {
                this.Emp_CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ADUser
        {
            get
            {
                return this.ADUserField;
            }
            set
            {
                this.ADUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] UserImage
        {
            get
            {
                return this.UserImageField;
            }
            set
            {
                this.UserImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TH_Name
        {
            get
            {
                return this.TH_NameField;
            }
            set
            {
                this.TH_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ENG_Name
        {
            get
            {
                return this.ENG_NameField;
            }
            set
            {
                this.ENG_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NickName
        {
            get
            {
                return this.NickNameField;
            }
            set
            {
                this.NickNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string PositionName
        {
            get
            {
                return this.PositionNameField;
            }
            set
            {
                this.PositionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Level
        {
            get
            {
                return this.LevelField;
            }
            set
            {
                this.LevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string SEX
        {
            get
            {
                return this.SEXField;
            }
            set
            {
                this.SEXField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Telephone
        {
            get
            {
                return this.TelephoneField;
            }
            set
            {
                this.TelephoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string NodeID
        {
            get
            {
                return this.NodeIDField;
            }
            set
            {
                this.NodeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string NodeName
        {
            get
            {
                return this.NodeNameField;
            }
            set
            {
                this.NodeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string DepartmentID
        {
            get
            {
                return this.DepartmentIDField;
            }
            set
            {
                this.DepartmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string BranchCode
        {
            get
            {
                return this.BranchCodeField;
            }
            set
            {
                this.BranchCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string CreateBy
        {
            get
            {
                return this.CreateByField;
            }
            set
            {
                this.CreateByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.DateTime CreateOn
        {
            get
            {
                return this.CreateOnField;
            }
            set
            {
                this.CreateOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string UpdateBy
        {
            get
            {
                return this.UpdateByField;
            }
            set
            {
                this.UpdateByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.DateTime UpdateOn
        {
            get
            {
                return this.UpdateOnField;
            }
            set
            {
                this.UpdateOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string OfficerCode
        {
            get
            {
                return this.OfficerCodeField;
            }
            set
            {
                this.OfficerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string PositionCode
        {
            get
            {
                return this.PositionCodeField;
            }
            set
            {
                this.PositionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string IDNumber
        {
            get
            {
                return this.IDNumberField;
            }
            set
            {
                this.IDNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public System.DateTime BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://tempuri.org/")]
    public partial class Department : ServiceReference1._Department
    {
        
        private ServiceReference1.ArrayOfString CostCenterField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ServiceReference1.ArrayOfString CostCenter
        {
            get
            {
                return this.CostCenterField;
            }
            set
            {
                this.CostCenterField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_Department", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Department))]
    public partial class _Department : object
    {
        
        private string DepartmentIDField;
        
        private string TH_DepartmentNameField;
        
        private string ENG_DepartmentNameField;
        
        private string ParentNodeField;
        
        private byte LevelField;
        
        private string ActiveField;
        
        private string CreateByField;
        
        private System.DateTime CreateOnField;
        
        private string UpdateByField;
        
        private System.DateTime UpdateOnField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DepartmentID
        {
            get
            {
                return this.DepartmentIDField;
            }
            set
            {
                this.DepartmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TH_DepartmentName
        {
            get
            {
                return this.TH_DepartmentNameField;
            }
            set
            {
                this.TH_DepartmentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ENG_DepartmentName
        {
            get
            {
                return this.ENG_DepartmentNameField;
            }
            set
            {
                this.ENG_DepartmentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ParentNode
        {
            get
            {
                return this.ParentNodeField;
            }
            set
            {
                this.ParentNodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public byte Level
        {
            get
            {
                return this.LevelField;
            }
            set
            {
                this.LevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CreateBy
        {
            get
            {
                return this.CreateByField;
            }
            set
            {
                this.CreateByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime CreateOn
        {
            get
            {
                return this.CreateOnField;
            }
            set
            {
                this.CreateOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string UpdateBy
        {
            get
            {
                return this.UpdateByField;
            }
            set
            {
                this.UpdateByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime UpdateOn
        {
            get
            {
                return this.UpdateOnField;
            }
            set
            {
                this.UpdateOnField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Group", Namespace="http://tempuri.org/")]
    public partial class Group : ServiceReference1._Group
    {
        
        private ServiceReference1.Permission[] PermissionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ServiceReference1.Permission[] Permissions
        {
            get
            {
                return this.PermissionsField;
            }
            set
            {
                this.PermissionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_Group", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Group))]
    public partial class _Group : object
    {
        
        private int GroupIDField;
        
        private string TH_GroupNameField;
        
        private string ENG_GroupNameField;
        
        private string DescriptionField;
        
        private string CreateByField;
        
        private System.DateTime CreateOnField;
        
        private string UpdateByField;
        
        private System.DateTime UpdateOnField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int GroupID
        {
            get
            {
                return this.GroupIDField;
            }
            set
            {
                this.GroupIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TH_GroupName
        {
            get
            {
                return this.TH_GroupNameField;
            }
            set
            {
                this.TH_GroupNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ENG_GroupName
        {
            get
            {
                return this.ENG_GroupNameField;
            }
            set
            {
                this.ENG_GroupNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CreateBy
        {
            get
            {
                return this.CreateByField;
            }
            set
            {
                this.CreateByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime CreateOn
        {
            get
            {
                return this.CreateOnField;
            }
            set
            {
                this.CreateOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string UpdateBy
        {
            get
            {
                return this.UpdateByField;
            }
            set
            {
                this.UpdateByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime UpdateOn
        {
            get
            {
                return this.UpdateOnField;
            }
            set
            {
                this.UpdateOnField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Permission", Namespace="http://tempuri.org/")]
    public partial class Permission : ServiceReference1._Permission
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_Permission", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Permission))]
    public partial class _Permission : object
    {
        
        private string PermissionIDField;
        
        private string SystemIDField;
        
        private string TH_PermissionNameField;
        
        private string ENG_PermissionNameField;
        
        private string CreateByField;
        
        private System.DateTime CreateOnField;
        
        private string UpdateByField;
        
        private System.DateTime UpdateOnField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PermissionID
        {
            get
            {
                return this.PermissionIDField;
            }
            set
            {
                this.PermissionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SystemID
        {
            get
            {
                return this.SystemIDField;
            }
            set
            {
                this.SystemIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TH_PermissionName
        {
            get
            {
                return this.TH_PermissionNameField;
            }
            set
            {
                this.TH_PermissionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ENG_PermissionName
        {
            get
            {
                return this.ENG_PermissionNameField;
            }
            set
            {
                this.ENG_PermissionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CreateBy
        {
            get
            {
                return this.CreateByField;
            }
            set
            {
                this.CreateByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime CreateOn
        {
            get
            {
                return this.CreateOnField;
            }
            set
            {
                this.CreateOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string UpdateBy
        {
            get
            {
                return this.UpdateByField;
            }
            set
            {
                this.UpdateByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime UpdateOn
        {
            get
            {
                return this.UpdateOnField;
            }
            set
            {
                this.UpdateOnField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.UserManagementSoap")]
    public interface UserManagementSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateTokenID", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CreateTokenIDResponse> CreateTokenIDAsync(ServiceReference1.CreateTokenIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenTokenID", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.AuthenTokenIDResponse> AuthenTokenIDAsync(ServiceReference1.AuthenTokenIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetAllUserResponse> GetAllUserAsync(ServiceReference1.GetAllUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetUserResponse> GetUserAsync(ServiceReference1.GetUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetUserByCodeResponse> GetUserByCodeAsync(ServiceReference1.GetUserByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserlogin", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CheckUserloginResponse> CheckUserloginAsync(ServiceReference1.CheckUserloginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeDepartmentTree", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetEmployeeDepartmentTreeResponse> GetEmployeeDepartmentTreeAsync(ServiceReference1.GetEmployeeDepartmentTreeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTeamUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetTeamUserResponse> GetTeamUserAsync(ServiceReference1.GetTeamUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTeam", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetAllTeamResponse> GetAllTeamAsync(ServiceReference1.GetAllTeamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateTeam", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CreateTeamResponse> CreateTeamAsync(ServiceReference1.CreateTeamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTeam", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.UpdateTeamResponse> UpdateTeamAsync(ServiceReference1.UpdateTeamRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTokenIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTokenID", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.CreateTokenIDRequestBody Body;
        
        public CreateTokenIDRequest()
        {
        }
        
        public CreateTokenIDRequest(ServiceReference1.CreateTokenIDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateTokenIDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.Token token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ServiceReference1.PreRequest PRequest;
        
        public CreateTokenIDRequestBody()
        {
        }
        
        public CreateTokenIDRequestBody(ServiceReference1.Token token, ServiceReference1.PreRequest PRequest)
        {
            this.token = token;
            this.PRequest = PRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTokenIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTokenIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.CreateTokenIDResponseBody Body;
        
        public CreateTokenIDResponse()
        {
        }
        
        public CreateTokenIDResponse(ServiceReference1.CreateTokenIDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateTokenIDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.AuthenticationMSG CreateTokenIDResult;
        
        public CreateTokenIDResponseBody()
        {
        }
        
        public CreateTokenIDResponseBody(ServiceReference1.AuthenticationMSG CreateTokenIDResult)
        {
            this.CreateTokenIDResult = CreateTokenIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenTokenIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenTokenID", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.AuthenTokenIDRequestBody Body;
        
        public AuthenTokenIDRequest()
        {
        }
        
        public AuthenTokenIDRequest(ServiceReference1.AuthenTokenIDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenTokenIDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.Token token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ServiceReference1.PreRequest PRequest;
        
        public AuthenTokenIDRequestBody()
        {
        }
        
        public AuthenTokenIDRequestBody(ServiceReference1.Token token, ServiceReference1.PreRequest PRequest)
        {
            this.token = token;
            this.PRequest = PRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenTokenIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenTokenIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.AuthenTokenIDResponseBody Body;
        
        public AuthenTokenIDResponse()
        {
        }
        
        public AuthenTokenIDResponse(ServiceReference1.AuthenTokenIDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenTokenIDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.AuthenticationMSG AuthenTokenIDResult;
        
        public AuthenTokenIDResponseBody()
        {
        }
        
        public AuthenTokenIDResponseBody(ServiceReference1.AuthenticationMSG AuthenTokenIDResult)
        {
            this.AuthenTokenIDResult = AuthenTokenIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUser", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetAllUserRequestBody Body;
        
        public GetAllUserRequest()
        {
        }
        
        public GetAllUserRequest(ServiceReference1.GetAllUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.PreRequest PRequest;
        
        public GetAllUserRequestBody()
        {
        }
        
        public GetAllUserRequestBody(ServiceReference1.PreRequest PRequest)
        {
            this.PRequest = PRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetAllUserResponseBody Body;
        
        public GetAllUserResponse()
        {
        }
        
        public GetAllUserResponse(ServiceReference1.GetAllUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.UserManagementMSG GetAllUserResult;
        
        public GetAllUserResponseBody()
        {
        }
        
        public GetAllUserResponseBody(ServiceReference1.UserManagementMSG GetAllUserResult)
        {
            this.GetAllUserResult = GetAllUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUser", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetUserRequestBody Body;
        
        public GetUserRequest()
        {
        }
        
        public GetUserRequest(ServiceReference1.GetUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ADUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ServiceReference1.PreRequest PRequest;
        
        public GetUserRequestBody()
        {
        }
        
        public GetUserRequestBody(string ADUser, ServiceReference1.PreRequest PRequest)
        {
            this.ADUser = ADUser;
            this.PRequest = PRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetUserResponseBody Body;
        
        public GetUserResponse()
        {
        }
        
        public GetUserResponse(ServiceReference1.GetUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.UserManagementMSG GetUserResult;
        
        public GetUserResponseBody()
        {
        }
        
        public GetUserResponseBody(ServiceReference1.UserManagementMSG GetUserResult)
        {
            this.GetUserResult = GetUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByCode", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetUserByCodeRequestBody Body;
        
        public GetUserByCodeRequest()
        {
        }
        
        public GetUserByCodeRequest(ServiceReference1.GetUserByCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserByCodeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ServiceReference1.PreRequest PRequest;
        
        public GetUserByCodeRequestBody()
        {
        }
        
        public GetUserByCodeRequestBody(string Code, ServiceReference1.PreRequest PRequest)
        {
            this.Code = Code;
            this.PRequest = PRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetUserByCodeResponseBody Body;
        
        public GetUserByCodeResponse()
        {
        }
        
        public GetUserByCodeResponse(ServiceReference1.GetUserByCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserByCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.UserManagementMSG GetUserByCodeResult;
        
        public GetUserByCodeResponseBody()
        {
        }
        
        public GetUserByCodeResponseBody(ServiceReference1.UserManagementMSG GetUserByCodeResult)
        {
            this.GetUserByCodeResult = GetUserByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserloginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserlogin", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.CheckUserloginRequestBody Body;
        
        public CheckUserloginRequest()
        {
        }
        
        public CheckUserloginRequest(ServiceReference1.CheckUserloginRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserloginRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ADUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ServiceReference1.PreRequest PRequest;
        
        public CheckUserloginRequestBody()
        {
        }
        
        public CheckUserloginRequestBody(string ADUser, string Password, ServiceReference1.PreRequest PRequest)
        {
            this.ADUser = ADUser;
            this.Password = Password;
            this.PRequest = PRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserloginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserloginResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.CheckUserloginResponseBody Body;
        
        public CheckUserloginResponse()
        {
        }
        
        public CheckUserloginResponse(ServiceReference1.CheckUserloginResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserloginResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.UserManagementMSG CheckUserloginResult;
        
        public CheckUserloginResponseBody()
        {
        }
        
        public CheckUserloginResponseBody(ServiceReference1.UserManagementMSG CheckUserloginResult)
        {
            this.CheckUserloginResult = CheckUserloginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeDepartmentTreeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeDepartmentTree", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetEmployeeDepartmentTreeRequestBody Body;
        
        public GetEmployeeDepartmentTreeRequest()
        {
        }
        
        public GetEmployeeDepartmentTreeRequest(ServiceReference1.GetEmployeeDepartmentTreeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeDepartmentTreeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ADUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ServiceReference1.PreRequest PRequest;
        
        public GetEmployeeDepartmentTreeRequestBody()
        {
        }
        
        public GetEmployeeDepartmentTreeRequestBody(string ADUser, ServiceReference1.PreRequest PRequest)
        {
            this.ADUser = ADUser;
            this.PRequest = PRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeDepartmentTreeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeDepartmentTreeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetEmployeeDepartmentTreeResponseBody Body;
        
        public GetEmployeeDepartmentTreeResponse()
        {
        }
        
        public GetEmployeeDepartmentTreeResponse(ServiceReference1.GetEmployeeDepartmentTreeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeDepartmentTreeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.UserManagementMSG GetEmployeeDepartmentTreeResult;
        
        public GetEmployeeDepartmentTreeResponseBody()
        {
        }
        
        public GetEmployeeDepartmentTreeResponseBody(ServiceReference1.UserManagementMSG GetEmployeeDepartmentTreeResult)
        {
            this.GetEmployeeDepartmentTreeResult = GetEmployeeDepartmentTreeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTeamUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTeamUser", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetTeamUserRequestBody Body;
        
        public GetTeamUserRequest()
        {
        }
        
        public GetTeamUserRequest(ServiceReference1.GetTeamUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTeamUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int TeamID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ServiceReference1.PreRequest PRequest;
        
        public GetTeamUserRequestBody()
        {
        }
        
        public GetTeamUserRequestBody(int TeamID, ServiceReference1.PreRequest PRequest)
        {
            this.TeamID = TeamID;
            this.PRequest = PRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTeamUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTeamUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetTeamUserResponseBody Body;
        
        public GetTeamUserResponse()
        {
        }
        
        public GetTeamUserResponse(ServiceReference1.GetTeamUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTeamUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.UserManagementMSG GetTeamUserResult;
        
        public GetTeamUserResponseBody()
        {
        }
        
        public GetTeamUserResponseBody(ServiceReference1.UserManagementMSG GetTeamUserResult)
        {
            this.GetTeamUserResult = GetTeamUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTeamRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTeam", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetAllTeamRequestBody Body;
        
        public GetAllTeamRequest()
        {
        }
        
        public GetAllTeamRequest(ServiceReference1.GetAllTeamRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTeamRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.PreRequest PRequest;
        
        public GetAllTeamRequestBody()
        {
        }
        
        public GetAllTeamRequestBody(ServiceReference1.PreRequest PRequest)
        {
            this.PRequest = PRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTeamResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTeamResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetAllTeamResponseBody Body;
        
        public GetAllTeamResponse()
        {
        }
        
        public GetAllTeamResponse(ServiceReference1.GetAllTeamResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTeamResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.UserManagementMSG GetAllTeamResult;
        
        public GetAllTeamResponseBody()
        {
        }
        
        public GetAllTeamResponseBody(ServiceReference1.UserManagementMSG GetAllTeamResult)
        {
            this.GetAllTeamResult = GetAllTeamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTeamRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTeam", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.CreateTeamRequestBody Body;
        
        public CreateTeamRequest()
        {
        }
        
        public CreateTeamRequest(ServiceReference1.CreateTeamRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateTeamRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.UserManagementMSG User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ServiceReference1.PreRequest PRequest;
        
        public CreateTeamRequestBody()
        {
        }
        
        public CreateTeamRequestBody(ServiceReference1.UserManagementMSG User, ServiceReference1.PreRequest PRequest)
        {
            this.User = User;
            this.PRequest = PRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTeamResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTeamResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.CreateTeamResponseBody Body;
        
        public CreateTeamResponse()
        {
        }
        
        public CreateTeamResponse(ServiceReference1.CreateTeamResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateTeamResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.UserManagementMSG CreateTeamResult;
        
        public CreateTeamResponseBody()
        {
        }
        
        public CreateTeamResponseBody(ServiceReference1.UserManagementMSG CreateTeamResult)
        {
            this.CreateTeamResult = CreateTeamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTeamRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTeam", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.UpdateTeamRequestBody Body;
        
        public UpdateTeamRequest()
        {
        }
        
        public UpdateTeamRequest(ServiceReference1.UpdateTeamRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateTeamRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.UserManagementMSG User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ServiceReference1.PreRequest PRequest;
        
        public UpdateTeamRequestBody()
        {
        }
        
        public UpdateTeamRequestBody(ServiceReference1.UserManagementMSG User, ServiceReference1.PreRequest PRequest)
        {
            this.User = User;
            this.PRequest = PRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTeamResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTeamResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.UpdateTeamResponseBody Body;
        
        public UpdateTeamResponse()
        {
        }
        
        public UpdateTeamResponse(ServiceReference1.UpdateTeamResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateTeamResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.UserManagementMSG UpdateTeamResult;
        
        public UpdateTeamResponseBody()
        {
        }
        
        public UpdateTeamResponseBody(ServiceReference1.UserManagementMSG UpdateTeamResult)
        {
            this.UpdateTeamResult = UpdateTeamResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface UserManagementSoapChannel : ServiceReference1.UserManagementSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class UserManagementSoapClient : System.ServiceModel.ClientBase<ServiceReference1.UserManagementSoap>, ServiceReference1.UserManagementSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UserManagementSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(UserManagementSoapClient.GetBindingForEndpoint(endpointConfiguration), UserManagementSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserManagementSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UserManagementSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserManagementSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UserManagementSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserManagementSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.CreateTokenIDResponse> ServiceReference1.UserManagementSoap.CreateTokenIDAsync(ServiceReference1.CreateTokenIDRequest request)
        {
            return base.Channel.CreateTokenIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CreateTokenIDResponse> CreateTokenIDAsync(ServiceReference1.Token token, ServiceReference1.PreRequest PRequest)
        {
            ServiceReference1.CreateTokenIDRequest inValue = new ServiceReference1.CreateTokenIDRequest();
            inValue.Body = new ServiceReference1.CreateTokenIDRequestBody();
            inValue.Body.token = token;
            inValue.Body.PRequest = PRequest;
            return ((ServiceReference1.UserManagementSoap)(this)).CreateTokenIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.AuthenTokenIDResponse> ServiceReference1.UserManagementSoap.AuthenTokenIDAsync(ServiceReference1.AuthenTokenIDRequest request)
        {
            return base.Channel.AuthenTokenIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AuthenTokenIDResponse> AuthenTokenIDAsync(ServiceReference1.Token token, ServiceReference1.PreRequest PRequest)
        {
            ServiceReference1.AuthenTokenIDRequest inValue = new ServiceReference1.AuthenTokenIDRequest();
            inValue.Body = new ServiceReference1.AuthenTokenIDRequestBody();
            inValue.Body.token = token;
            inValue.Body.PRequest = PRequest;
            return ((ServiceReference1.UserManagementSoap)(this)).AuthenTokenIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetAllUserResponse> ServiceReference1.UserManagementSoap.GetAllUserAsync(ServiceReference1.GetAllUserRequest request)
        {
            return base.Channel.GetAllUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetAllUserResponse> GetAllUserAsync(ServiceReference1.PreRequest PRequest)
        {
            ServiceReference1.GetAllUserRequest inValue = new ServiceReference1.GetAllUserRequest();
            inValue.Body = new ServiceReference1.GetAllUserRequestBody();
            inValue.Body.PRequest = PRequest;
            return ((ServiceReference1.UserManagementSoap)(this)).GetAllUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetUserResponse> ServiceReference1.UserManagementSoap.GetUserAsync(ServiceReference1.GetUserRequest request)
        {
            return base.Channel.GetUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetUserResponse> GetUserAsync(string ADUser, ServiceReference1.PreRequest PRequest)
        {
            ServiceReference1.GetUserRequest inValue = new ServiceReference1.GetUserRequest();
            inValue.Body = new ServiceReference1.GetUserRequestBody();
            inValue.Body.ADUser = ADUser;
            inValue.Body.PRequest = PRequest;
            return ((ServiceReference1.UserManagementSoap)(this)).GetUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetUserByCodeResponse> ServiceReference1.UserManagementSoap.GetUserByCodeAsync(ServiceReference1.GetUserByCodeRequest request)
        {
            return base.Channel.GetUserByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetUserByCodeResponse> GetUserByCodeAsync(string Code, ServiceReference1.PreRequest PRequest)
        {
            ServiceReference1.GetUserByCodeRequest inValue = new ServiceReference1.GetUserByCodeRequest();
            inValue.Body = new ServiceReference1.GetUserByCodeRequestBody();
            inValue.Body.Code = Code;
            inValue.Body.PRequest = PRequest;
            return ((ServiceReference1.UserManagementSoap)(this)).GetUserByCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.CheckUserloginResponse> ServiceReference1.UserManagementSoap.CheckUserloginAsync(ServiceReference1.CheckUserloginRequest request)
        {
            return base.Channel.CheckUserloginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CheckUserloginResponse> CheckUserloginAsync(string ADUser, string Password, ServiceReference1.PreRequest PRequest)
        {
            ServiceReference1.CheckUserloginRequest inValue = new ServiceReference1.CheckUserloginRequest();
            inValue.Body = new ServiceReference1.CheckUserloginRequestBody();
            inValue.Body.ADUser = ADUser;
            inValue.Body.Password = Password;
            inValue.Body.PRequest = PRequest;
            return ((ServiceReference1.UserManagementSoap)(this)).CheckUserloginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetEmployeeDepartmentTreeResponse> ServiceReference1.UserManagementSoap.GetEmployeeDepartmentTreeAsync(ServiceReference1.GetEmployeeDepartmentTreeRequest request)
        {
            return base.Channel.GetEmployeeDepartmentTreeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetEmployeeDepartmentTreeResponse> GetEmployeeDepartmentTreeAsync(string ADUser, ServiceReference1.PreRequest PRequest)
        {
            ServiceReference1.GetEmployeeDepartmentTreeRequest inValue = new ServiceReference1.GetEmployeeDepartmentTreeRequest();
            inValue.Body = new ServiceReference1.GetEmployeeDepartmentTreeRequestBody();
            inValue.Body.ADUser = ADUser;
            inValue.Body.PRequest = PRequest;
            return ((ServiceReference1.UserManagementSoap)(this)).GetEmployeeDepartmentTreeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetTeamUserResponse> ServiceReference1.UserManagementSoap.GetTeamUserAsync(ServiceReference1.GetTeamUserRequest request)
        {
            return base.Channel.GetTeamUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetTeamUserResponse> GetTeamUserAsync(int TeamID, ServiceReference1.PreRequest PRequest)
        {
            ServiceReference1.GetTeamUserRequest inValue = new ServiceReference1.GetTeamUserRequest();
            inValue.Body = new ServiceReference1.GetTeamUserRequestBody();
            inValue.Body.TeamID = TeamID;
            inValue.Body.PRequest = PRequest;
            return ((ServiceReference1.UserManagementSoap)(this)).GetTeamUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetAllTeamResponse> ServiceReference1.UserManagementSoap.GetAllTeamAsync(ServiceReference1.GetAllTeamRequest request)
        {
            return base.Channel.GetAllTeamAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetAllTeamResponse> GetAllTeamAsync(ServiceReference1.PreRequest PRequest)
        {
            ServiceReference1.GetAllTeamRequest inValue = new ServiceReference1.GetAllTeamRequest();
            inValue.Body = new ServiceReference1.GetAllTeamRequestBody();
            inValue.Body.PRequest = PRequest;
            return ((ServiceReference1.UserManagementSoap)(this)).GetAllTeamAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.CreateTeamResponse> ServiceReference1.UserManagementSoap.CreateTeamAsync(ServiceReference1.CreateTeamRequest request)
        {
            return base.Channel.CreateTeamAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CreateTeamResponse> CreateTeamAsync(ServiceReference1.UserManagementMSG User, ServiceReference1.PreRequest PRequest)
        {
            ServiceReference1.CreateTeamRequest inValue = new ServiceReference1.CreateTeamRequest();
            inValue.Body = new ServiceReference1.CreateTeamRequestBody();
            inValue.Body.User = User;
            inValue.Body.PRequest = PRequest;
            return ((ServiceReference1.UserManagementSoap)(this)).CreateTeamAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.UpdateTeamResponse> ServiceReference1.UserManagementSoap.UpdateTeamAsync(ServiceReference1.UpdateTeamRequest request)
        {
            return base.Channel.UpdateTeamAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.UpdateTeamResponse> UpdateTeamAsync(ServiceReference1.UserManagementMSG User, ServiceReference1.PreRequest PRequest)
        {
            ServiceReference1.UpdateTeamRequest inValue = new ServiceReference1.UpdateTeamRequest();
            inValue.Body = new ServiceReference1.UpdateTeamRequestBody();
            inValue.Body.User = User;
            inValue.Body.PRequest = PRequest;
            return ((ServiceReference1.UserManagementSoap)(this)).UpdateTeamAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UserManagementSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.UserManagementSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UserManagementSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://172.17.9.68/wsuser/usermanagement.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.UserManagementSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://172.17.9.68/wsuser/usermanagement.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            UserManagementSoap,
            
            UserManagementSoap12,
        }
    }
}
