// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using TCRB.DAL.Entity;

namespace TCRB.DAL.DBContext
{
    public class Ms_ChannelConfiguration : IEntityTypeConfiguration<Ms_Channel>
    {
        public void Configure(EntityTypeBuilder<Ms_Channel> entity)
        {
            entity.Property(e => e.ID).HasDefaultValueSql("(newsequentialid())");

            entity.Property(e => e.IsActive)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValueSql("('Y')");
        }
    }
}
