declare @LINK nvarchar(20)
	SET @LINK	= ISNULL(@LINK, 'AS400_UAT')
declare @SELECT nvarchar(MAx)
	SET @SELECT = ISNULL(@SELECT, 'L.CIFNO,COLD.CCDNAM, COLD.CCLOC1, COLD.CCLOC2, COLD.CCLOC3')
declare @CIFNO nvarchar(20)
	SET @CIFNO	= ISNULL(@CIFNO, '54010954')
DECLARE @TSQL NVARCHAR(MAX)



	
	SET @TSQL = 'SELECT CONCAT(CCDNAM,''  '', CCLOC1,''  '', CCLOC2,''  '', CCLOC3)  AS Resutl FROM OPENQUERY(AS400_UAT,
	''SELECT DISTINCT '+ @SELECT +'   
		FROM TCPDATMAS.LNMAST L INNER JOIN TCPDATMAS.CFCOLX COLX ON L.ACCTNO=COLX.ACCTNO 
			LEFT JOIN TCPDATMAS.CFCOLD COLD ON COLX.CCDCID = COLD.CCDCID   
		WHERE L.CIFNO='+ @CIFNO +' AND CCLOC1<>''''''''  '')';
	
	EXEC(@TSQL)



	SET @TSQL = 'SELECT STUFF((
	SELECT CCDNAM + ''  ''+ CCLOC1+''  ''+ CCLOC2+''  ''+ CCLOC3   + ''<br>'' 
	FROM OPENQUERY(AS400_UAT,
	''SELECT DISTINCT '+ @SELECT +'   
		FROM TCPDATMAS.LNMAST L INNER JOIN TCPDATMAS.CFCOLX COLX ON L.ACCTNO=COLX.ACCTNO 
			LEFT JOIN TCPDATMAS.CFCOLD COLD ON COLX.CCDCID = COLD.CCDCID   
		WHERE L.CIFNO='+ @CIFNO +' AND CCLOC1<>''''''''  '')
		FOR XML PATH('''') ,TYPE).value(''text()[1]'',''nvarchar(max)''),1,2,N'''') AS Result
		';
	
	print(@TSQL)
	EXEC (@TSQL)




