--sp_GetResult01
--Mobile,Birth
--ok
--CFSSNO
SELECT * FROM OPENQUERY(AS400_UAT,'SELECT CFBFHO AS MOBILENO, CFBIRD AS DATEOFBIRTH
FROM TCPDATMAS.CFMAST WHERE CFCIFN=55022675')

--sp_GetAddressCurrentResult
--AddressCurrent
--ok
SELECT * FROM OPENQUERY(AS400_UAT,'SELECT CFA.CFNA2,CFA.CFNA3,CFA.CFNA4,CFA.CFNA5,CFA.CFNA6,CFA.CFNA7 FROM TCPDATMAS.CFADDR AS CFA INNER JOIN TCPDATMAS.CFADRM AS CFADRM 
ON CFADRM.CFCIFN = CFA.CFCIFN AND CFA.CFADSQ = CFADRM.CFADSQ   WHERE CFA.CFCIFN=55022675 AND CFADRM.CFADRT = 1 ')

--sp_GetResult03
--Branch,LastPaymentDate,LastPaymentAmount,TERM,ORGAMT,TYPE_DESC,ReleaseDate
--ok
SELECT * FROM OPENQUERY(AS400_UAT,'SELECT L.FRELDT AS RELEASEDATE,L.PMTAMT,L.TYPE,PAR.PTYDSC AS TYPE_DESC,ORGAMT,TERM,BRN AS BRANCH,LPDT AS LASTPAYMENTDATE,LSTPMT AS LASTPAYMENTAMOUNT
FROM TCPDATMAS.LNMAST L INNER JOIN TCPDATPAR.LNPAR2 PAR ON L.TYPE=PAR.PTYPE WHERE L.CIFNO=55022675')

--sp_GetResult04
--ผู้ค้ำ
--Guarantor
--OK
SELECT * FROM OPENQUERY(AS400_UAT,'SELECT CFM.CFSNME AS NAME_GO FROM TCPDATMAS.LNMAST L INNER JOIN TCPDATMAS.CFACCT A ON L.ACCTNO=A.CFACCN 
INNER JOIN TCPDATMAS.CFMAST CFM ON A.CFCIFN=CFM.CFCIFN
WHERE L.CIFNO=67000064 AND  A.CFRELA=''GO''')

--sp_GetborrowerResult
--ผู้กู้ร่วม
--co-borrower
--OK
SELECT * FROM OPENQUERY(AS400_UAT,'SELECT CFM.CFSNME AS NAME_JT FROM TCPDATMAS.LNMAST L INNER JOIN TCPDATMAS.CFACCT A ON L.ACCTNO=A.CFACCN 
INNER JOIN TCPDATMAS.CFMAST CFM ON A.CFCIFN=CFM.CFCIFN
WHERE L.CIFNO=67000069 AND  A.CFRELA=''JT''')

--sp_GetResult06
--Address Collateral
--OK
SELECT * FROM OPENQUERY(AS400_UAT,' SELECT DISTINCT L.CIFNO,COLD.CCDNAM,COLD.CCLOC1,COLD.CCLOC2,COLD.CCLOC3 FROM TCPDATMAS.LNMAST L INNER JOIN TCPDATMAS.CFCOLX COLX ON L.ACCTNO=COLX.ACCTNO 
LEFT JOIN TCPDATMAS.CFCOLD COLD ON COLX.CCDCID = COLD.CCDCID  WHERE CCLOC1<>'''' AND L.CIFNO=54010954')

--sp_GetResult02 ok
--Brand,RegistrationNo,Model
SELECT * FROM OPENQUERY(AS400_UAT,'SELECT COLD.CCBRGN AS REGISTRATIONNO,PD.HPDDES AS BRAND,PE.HPEDES AS MODEL FROM TCPDATMAS.LNMAST L INNER JOIN TCPDATMAS.CFCOLX CX ON L.ACCTNO=CX.ACCTNO 
INNER JOIN TCPDATMAS.HPMAST H ON CX.ACCTNO=H.HPACCT 
LEFT JOIN TCPDATMAS.CFCOLD COLD ON CX.CCDCID = COLD.CCDCID 
INNER JOIN TCPDATPAR.HPPARG G ON H.HPVEQH = G.HPGCOD 
LEFT JOIN TCPDATPAR.HPPARD PD ON G.HPGBRA=PD.HPDCOD 
LEFT JOIN TCPDATPAR.HPPARE PE ON G.HPGMOD=PE.HPECOD
WHERE L.CIFNO=1000001 AND COLD.CCBRGN<>'''' ' )

--Get CifNo
SELECT * FROM OPENQUERY(AS400_UAT,'SELECT *, C
FROM TCPDATMAS.CFMAST WHERE CFCIFN=55022675')