declare @LINK nvarchar(20)
	SET @LINK	= ISNULL(@LINK, 'AS400_UAT')
declare @SELECT nvarchar(MAx)
	SET @SELECT = ISNULL(@SELECT, 'L.CIFNO,COLD.CCDNAM, COLD.CCLOC1, COLD.CCLOC2, COLD.CCLOC3')
declare @CIFNO nvarchar(20)
	SET @CIFNO	= ISNULL(@CIFNO, '1000001')
DECLARE @TSQL NVARCHAR(MAX)



	
	--SET @TSQL = 'SELECT CONCAT(CCDNAM,''  '', CCLOC1,''  '', CCLOC2,''  '', CCLOC3)  AS Resutl FROM OPENQUERY(AS400_UAT,
	--''SELECT DISTINCT '+ @SELECT +'   
	--	FROM TCPDATMAS.LNMAST L INNER JOIN TCPDATMAS.CFCOLX COLX ON L.ACCTNO=COLX.ACCTNO 
	--		LEFT JOIN TCPDATMAS.CFCOLD COLD ON COLX.CCDCID = COLD.CCDCID   
	--	WHERE L.CIFNO='+ @CIFNO +' AND CCLOC1<>''''''''  '')';
	
	--EXEC(@TSQL)

	
	SET @TSQL = 'SELECT 
						MobileNo
						,dbo.getDate7(null) as DateOfBirth
					FROM OPENQUERY('+ @LINK +',
								''SELECT CFBFHO AS MobileNo
										,CFBIRD AS DateOfBirth 
								FROM TCPDATMAS.CFMAST WHERE CFCIFN='+ @CIFNO +' '')';	
	
	--print(@TSQL)
	EXEC (@TSQL)




